name: Trigger Tosca SAP Execution

on:
  workflow_dispatch:

jobs:
  run-batch:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Batch File
        working-directory: EventFiles
        run: cmd /c "RunPOCEvent.bat"
        shell: cmd
