name: Trigger Tosca SAP Execution

# Trigger the workflow manually
on:
  workflow_dispatch:
    inputs:
      events:
        description: 'Events value'
        required: false
        default: '["DEX Standalone"]' # Default value as a JSON array

jobs:
  run-tosca:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run the Tosca Execution Client
      - name: Run Batch File
        run: |
          echo "Running POC batch file..."
          .\RunPOCEvent.bat
