name: Trigger Tosca

# Trigger the workflow manually
on:
  workflow_dispatch:
    inputs:
      events:
        description: 'Events value'
        required: false
        default: '["DEX Standalone"]' # Default value as a JSON array

jobs:
  run-tosca:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run the Tosca Execution Client
      - name: Run Tosca Execution Client
        run: pwsh ./ToscaExecutionClient-main/tosca_execution_client.ps1 -toscaServerUrl "https://awstoscap01.idexxi.com" -events '${{ github.event.inputs.events }}' -projectName "IDEXX_Salesforce_Automation" -clientId "${{ secrets.PhWpOWsQPkGsto-JRKpSqw }}" -clientSecret "${{ secrets.ux0Nqp6-fUC4covZX2Z68w1uoqvzbto0mMJLxlnJ-sZQ }}"
